"""initial schema

Revision ID: 017b6a76afec
Revises: 
Create Date: 2026-08-23 12:28:02.263560
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '017b6a76afec'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('investigator', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('heuristic', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_address', sa.String(length=64), nullable=False),
    sa.Column('to_address', sa.String(length=64), nullable=True),
    sa.Column('value_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('gas_price_wei', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_from_address'), ['from_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_to_address'), ['to_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_hash'), ['tx_hash'], unique=False)
        batch_op.create_index('ix_tx_from_ts', ['from_address', 'timestamp'], unique=False)
        batch_op.create_index('ix_tx_to_ts', ['to_address', 'timestamp'], unique=False)

    op.create_table('vasps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('CENTRALIZED_EXCHANGE', 'DEX', 'CUSTODIAN', 'PAYMENT_PROCESSOR', 'OTHER', name='vaspcategory'), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vasps'))
    )
    with op.batch_alter_table('vasps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vasps_name'), ['name'], unique=True)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('is_contract', sa.Boolean(), nullable=False),
    sa.Column('tx_count', sa.BigInteger(), nullable=False),
    sa.Column('balance_wei', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets'))
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_address'), ['address'], unique=True)

    op.create_table('cluster_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_cluster_members_cluster_id_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_members')),
    sa.UniqueConstraint('cluster_id', 'address', name='uq_cluster_member')
    )
    with op.batch_alter_table('cluster_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_members_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_members_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='findingseverity'), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_findings_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_case_id'), ['case_id'], unique=False)

    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.Enum('EXCHANGE', 'MIXER', 'SANCTIONED', 'DEFI', 'BRIDGE', 'GAMBLING', 'SCAM', 'CONTRACT', 'OTHER', name='labelcategory'), nullable=False),
    sa.Column('source', sa.Enum('ETHEREUM_LISTS', 'OFAC_SDN', 'ETHERSCAN_TAG', 'MANUAL', name='labelsource'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('vasp_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vasp_id'], ['vasps.id'], name=op.f('fk_labels_vasp_id_vasps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels')),
    sa.UniqueConstraint('address', 'source', 'name', name='uq_label_addr_src_name')
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_address'), ['address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_address'))

    op.drop_table('labels')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_case_id'))

    op.drop_table('findings')
    with op.batch_alter_table('cluster_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_members_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_members_address'))

    op.drop_table('cluster_members')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_address'))

    op.drop_table('wallets')
    with op.batch_alter_table('vasps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vasps_name'))

    op.drop_table('vasps')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_to_ts')
        batch_op.drop_index('ix_tx_from_ts')
        batch_op.drop_index(batch_op.f('ix_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_to_address'))
        batch_op.drop_index(batch_op.f('ix_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_from_address'))

    op.drop_table('transactions')
    op.drop_table('clusters')
    op.drop_table('cases')
    # ### end Alembic commands ###
