"""add case officer ownership

Revision ID: 2667ab6a85b4
Revises: 3954add2657d
Create Date: 2026-08-24 15:23:56.815366
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2667ab6a85b4'
down_revision: str | None = '3954add2657d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('officer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cases_officer_id'), 'cases', ['officer_id'], unique=False)
    op.create_foreign_key(op.f('fk_cases_officer_id_officers'), 'cases', 'officers', ['officer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cases_officer_id_officers'), 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_officer_id'), table_name='cases')
    op.drop_column('cases', 'officer_id')
    # ### end Alembic commands ###
