"""add investigation snapshots

Revision ID: 3954add2657d
Revises: b90c958951d9
Create Date: 2026-08-24 15:10:11.231513
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3954add2657d'
down_revision: str | None = 'b90c958951d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('provider_source', sa.String(length=32), nullable=False),
    sa.Column('traversal_max_hops', sa.Integer(), nullable=False),
    sa.Column('traversal_max_nodes', sa.Integer(), nullable=False),
    sa.Column('traversal_min_value_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('attribution', sa.JSON(), nullable=False),
    sa.Column('risk', sa.JSON(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=True),
    sa.Column('evidence_hops', sa.Integer(), nullable=True),
    sa.Column('evidence_tx_hashes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], name=op.f('fk_investigations_officer_id_officers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_officer_id'), 'investigations', ['officer_id'], unique=False)
    op.create_index(op.f('ix_investigations_wallet_address'), 'investigations', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_wallet_address'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_officer_id'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
